### ISSUE TITLE
docker latest版本豆瓣api500错误

### ISSUE THREAD

**Issue by a87750530** [talebook/calibre-webserver#31]
服务器异常，状态码：500 
请查阅服务器日志：
calibre-webserver.log

/api/book/3/refer (**ip*)
    HTTPServerRequest(protocol='http', host='*ip**', method='GET', uri='/api/book/3/refer', version='HTTP/1.0', remote_ip='**ip*')
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/var/www/calibre-webserver/webserver/handlers/base_handlers.py", line 54, in do
        rsp = func(self, *args, **kwargs)
      File "/var/www/calibre-webserver/webserver/handlers/base_handlers.py", line 68, in do
        return func(self, *args, **kwargs)
      File "/var/www/calibre-webserver/webserver/handlers/book_handlers.py", line 262, in get
        book = api.get_book(title)
      File "/var/www/calibre-webserver/webserver/baike.py", line 20, in get_book
        baike = self._baike(title)
      File "/var/www/calibre-webserver/webserver/baike.py", line 25, in _baike
        from baidubaike import Page
      File "/usr/local/lib/python2.7/dist-packages/baidubaike/__init__.py", line 1, in <module>
        from baidubaike import *
      File "/usr/local/lib/python2.7/dist-packages/baidubaike/baidubaike.py", line 7, in <module>
        from bs4 import BeautifulSoup
    ImportError: No module named bs4

**Comment by talebook** [comment]
已经在develop版本中修复。近期会合并到主干中
